'use client'
import '../globals.css';
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google';
import styles from './page.module.css'
import { useRouter } from 'next/router';

import Header from '@/components/Header/Header'
import LikeStockTab from '@/components/LikeStockTab/LikeStockTab'
import MainTabsPage from './[tab]/page'
import Chart from '@/components/chart/chart'

import { usePathname } from "next/navigation";



const sans = Open_Sans({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {

  // const tab = '1'
  const tab = usePathname()
  // const tab = usePathname() === '/' ? '1' : usePathname();
  // typeof tab === 'string' ? tab : 'default';tab
  // const tabValue = typeof tab === 'string' ? tab : 'default';
  // console.log(tab)
  return (
    <html lang="en">
      <body className={sans.className}>
        <Header />
        <div className={styles["mainpage"]}>
          <div className={styles["like-container"]}>
            <div className={styles["like-tab"]}>
              <div className={styles["like-tab-sticky"]}>
                <LikeStockTab />
              </div>
            </div>
          </div>
          <div>
            <div className='components'>
              <Chart />
            </div>
            <div>
              뉴스 보여지는 곳
            </div>
          </div>
            <div>
              {/* {children} */}
            </div>
            <div className={styles["Side-container"]}>
              <MainTabsPage params={{ tab }}/>
            </div>
        </div>
      </body>
    </html>
  )
}
